// Placeholder Firebase options. Replace with real values generated by `flutterfire configure`.
// DO NOT COMMIT REAL SECRETS.
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Single dev config (Android placeholder). For iOS/Web eklemeniz gerekebilir.
    return const FirebaseOptions(
      apiKey: 'AIzaSyBrKaICdApZeFXnGmfIwUFcYanXt7fI9lE',
      appId: '1:889040595041:android:69b8616ff225377e352220',
      messagingSenderId: '889040595041',
      projectId: 'quranlingo-06',
      storageBucket: 'quranlingo-06.firebasestorage.app',
    );
  }
}
